name: znc-modules-ondra
summary: custom modules for ZNC advanced IRC
description: |
   custom modules for ZNC advanced IRC bouncer

confinement: strict
grade: stable
adopt-info: znc
base: core18

slots:
    modules:
        interface: content
        content: modules
        read:
            - $SNAP/modules

parts:
    znc:
        plugin: nil
        override-pull: |
            snap download znc-ondra --edge
            unsquashfs -d snap znc-ondra*.snap -e usr
            mv snap/usr ${SNAPCRAFT_PART_INSTALL}/
            snapcraftctl set-version $(grep "VERSION_STR" ${SNAPCRAFT_PART_INSTALL}/usr/include/znc/version.h | awk '{print $3}' | sed 's/\"//g')
        build-packages:
            - cmake
            - libicu-dev
            - libperl-dev
            - libsasl2-dev
            - libssl-dev
            - pkg-config
            - python3-dev
            - swig3.0
            - tcl-dev
        prime:
            - -usr

    colloquypush:
        after:
            - znc
        plugin: nil
        source: https://github.com/kubiko/colloquypush.git
        source-type: git
        override-build: |
            znc-buildmod znc/colloquy.cpp
            cp *.so ${SNAPCRAFT_PART_INSTALL}
        organize:
            '*.so': modules/

    znc-palaver:
        after:
            - znc
        plugin: nil
        source: https://github.com/Palaver/znc-palaver.git
        source-type: git
        override-build: |
            znc-buildmod palaver.cpp
            cp *.so ${SNAPCRAFT_PART_INSTALL}
        organize:
            '*.so': modules/

    znc-playback:
        after:
            - znc
        plugin: nil
        source: https://github.com/jpnurmi/znc-playback.git
        source-type: git
        override-build: |
            znc-buildmod *.cpp
            cp *.so ${SNAPCRAFT_PART_INSTALL}
        organize:
            '*.so': modules/

    znc-push:
        after:
            - znc
        plugin: nil
        source: https://github.com/jreese/znc-push.git
        source-type: git
        override-build: |
            znc-buildmod *.cpp
            cp *.so ${SNAPCRAFT_PART_INSTALL}
        organize:
            '*.so': modules/

    znc-clientbuffer:
        after:
            - znc
        plugin: nil
        source: https://github.com/CyberShadow/znc-clientbuffer.git
        source-type: git
        override-build: |
            znc-buildmod *.cpp
            cp *.so ${SNAPCRAFT_PART_INSTALL}
        organize:
            '*.so': modules/

    mutter-znc:
        after:
            - znc
        plugin: dump
        source: https://github.com/seansweda/mutter-push.git
        organize:
            'mutter.py': modules/mutter.py
        prime:
            - modules
